package bht.tools.comps;

import java.awt.Container;

/**
 * An extension of a JPanel which contains convenience methods.
 * @author Supuhstar
 * @since Jun 23, 2011, 3:55:08 AM
 * @version 1.0.0
 */
public class BHContainer extends Container
{
  /** Creates new form BHContainer */
  public BHContainer()
  {
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
  
  /**
   * A convenience method that 
   * @return 
   */
  public java.awt.Window getParentWindow()
  {
    return BHCompUtilities.getParentWindowOf(this);
  }
}
